### ISSUE TITLE
Support new units attribute of `wc_lang.Concentration`

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/wc_sim#16]
One way to simplify this to avoid the need for arbitrary unit conversions is to make `wc_lang.Concentration.units` an enumeration:

- Molar (and potentially SI prefixes)
  - M, mM, uM, nM, pM, fM, aM
- molecules

**Comment by artgoldberg** [comment]
Supported in ffad8eef497637da58c042be0add4437f567f461
