### ISSUE TITLE
Make MW>0 check optional

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/wc_sim#25]

**Comment by artgoldberg** [comment]
These changes are needed for a proper fix:
Add a command line argument: change wc_sim/wc_sim/multialgorithm/__main__.py
Pass the argument to the simulator: wc_sim/wc_sim/multialgorithm/simulation.py
Pass argument to the model check code in _prepare()
Modify model checking code in: wc_lang/wc_lang/prepare.py
Don’t call ‘verify_species_types’

**Comment by jonrkarr** [comment]
wc-lang now allows `Species.molecular_weight` = 0 (negative molecular weights are not allowed)
