### ISSUE TITLE
Propensities to run_results

### ISSUE THREAD

**Issue by balazs1987** [KarrLab/wc_sim#28]
It would be useful to add more dataframes to the run_results. Specifically, it would be useful to record here:
- the propensities of reactions (after the reaction closest to the checkpoint has fired)
- the abundance of species in concentration space, not just copy numbers

These would be enormously useful for me now when trying to calibrate the models. 

I know that the information above could be obtained from the logs, but since log files record information on a per event basis, they can be prohibitively large. 

Probably in the long run, the the user should be given some control in what variables are saved in the pickle files.

**Comment by artgoldberg** [comment]
the abundance of species in concentration space will be available in my next push.

**Comment by artgoldberg** [comment]
"species concentrations" is done.

**Comment by artgoldberg** [comment]
"propensities of reactions" added to `RunResults` as rate_laws. 
Concentrations added earlier as `RunResults.get_concentrations`.
