### ISSUE TITLE
Separate core into distinct, public repo

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/wc_sim#3]

**Comment by jonrkarr** [comment]
Created `desim` repo for this. Currently, this is just a skeleton for the core module.

**Comment by artgoldberg** [comment]
todo

1. move default_center_of_mass to multialgorithm/config/core.default.cfg
2. stop using and delete wc_sim.core
keep these:
sim_config.py
de_sim/sim_metadata.py

**Comment by artgoldberg** [comment]
Finished:

- Rename `desim` to `de_sim`
- Move `wc_sim.core` to `de_sim`
- Have `wc_sim` use `de_sim`
- Move `default_center_of_mass` to `multialgorithm/config/core.default.cfg`

**Comment by artgoldberg** [comment]
Finished
- stop using and delete wc_sim.core
- move default_center_of_mass to multialgorithm/config/core.default.cfg
- move its issues to de_sim

Todo
- rm duplicate Checkpoint in wc_sim

**Comment by artgoldberg** [comment]
Finished
- rm duplicate Checkpoint in wc_sim

**Comment by artgoldberg** [comment]
Removed extra layer of nesting of `wc_sim.multialgorithm` within `wc_sim`
