### ISSUE TITLE
Support dynamic compartment volumes

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/wc_sim#34]

**Comment by artgoldberg** [comment]
dynamic compartment volume is already supported via V = mass/density in biochemical compartments. But I suspect you want another way to specify V varying with time.  How would that be specified?

**Comment by jonrkarr** [comment]
wc-sim no longer needs to calculate compartment volumes. I've re-factored wc-lang so that modelers can define functions for volumes and how they should be calculated. 

This is the scheme for dynamic calculation of volumes and their usage in rate laws:
1.  wc-sim calculates the total mass of each compartment
2. Modeler's define a density parameter for each compartment (`wc_lang.Compartment.density`)
3. If necessary, modeler's define a volume function for each compartment (`wc_lang.Function`) whose expression (`wc_lang.Function.expression.expression`) is equal to `comp_id / comp_density_param_id`
4. Modelers can use these functions in rate laws (e.g. `v = k_cat * E[c] * S[c] / (K_m * Avogadro * c + S[c])` where the units of `E[c]` and `S[c]` are molecule

The other place where we're doing calculations that involve volume is during the calculation of initial conditions which can be specified as (random distributions of) volumes of compartments and (random distributions of) concentrations. This is the intended scheme:
1. Modeler defines the random distributions of compartment volumes (`wc_lang.Compartment.mean_init_volume`)
2. Molecular defines the random distribution of species counts/concentrations (`wc_lang.DistributionInitConcentration`)
3. wc-sim samples from the random distributions of compartment volumes
4. wc-sim samples from the random distribution of species counts/concentrations. For concentration-valued quantities, wc-sim uses the compartment volumes sampled from Step 3.
5. After the initial conditions are sampled, wc-sim sets the values of the density parameters of each compartment (`wc_lang.Compartment.density.value`) equal to `comp.mass() / comp.init_volume`

**`wc_sim.multialgorithm.multialgorithm_simulation` needs to refactored to implement Step 4.**

**Comment by johnsekar** [comment]
Here, it would make sense to have volume sampling outside the main wc-sim
framework. Defining a distribution of initial conditions is more correctly
a simulation protocol rather than a part of the model structure.

**Comment by artgoldberg** [comment]
done
