### ISSUE TITLE
Address issues noted in wc_lang.expression_utils

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/wc_sim#40]
- put dict of submodels in dynamic_model
- give abstract compartments control over their volumes
- can a reaction's reactants and modifiers be contained in multiple compartments
- ensure that all related objects made before their using objects in DynamicModel.__init__()
- handle any multiplicity of StopConditions; allow execution to choose among multiple StopConditions, or use them all

**Comment by jonrkarr** [comment]
- Volume is now a function in wc_lang; wc-sim only needs to calculate the mass of each compartment
- wc_lang allows the reactants, products, and modifiers of each reaction to be in 1 or multiple compartments

**Comment by artgoldberg** [comment]
Done

- put dict of submodels in dynamic_model
- ensure that all related objects made before their using objects in DynamicModel.init()
- handle any multiplicity of StopConditions

To do later

- allow execution to choose among multiple StopConditions, or use them all
- give abstract compartments control over their volumes
