### ISSUE TITLE
Failure to validate reading of examples/translation_metabolism_hybrid_model/model.xlsx

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/wc_sim#51]

**Comment by artgoldberg** [comment]
Fails on Circle repeatedly, but not locally. Unclear why. Related to ChemicalStructure.

**Comment by artgoldberg** [comment]
Jonathan, could you look at this validation failure please? I'm not familiar with the ChemicalStructure code, and it passes in my Docker container.

Thanks.

**Comment by jonrkarr** [comment]
Fixed. 

Test failure was triggered by a correction to the `BpForms` protein alphabet (correcting `BpForms` helped find an error in the `wc_sim` example).
